### ISSUE TITLE
404 on webdav folder: GET and PUT not possible

### ISSUE THREAD

**Issue by tchncs** [hacdias/caddy-filemanager#70]
Hi there, i am currently with Revision `15e46f9`.
When i try to upload a file, it fails with:
`"PUT /user/webdav/testimage.jpg HTTP/2.0" 404 9`

My caddyfile entry contains:

```
        basicauth /user user very_secure

        filemanager /user {
                show            /home/mh-users/user
                allow_new       true
                allow_edit      true
                block           /my/secret
                user:
                allow_command   git
        }
``` 

On an older version i just fixed that by creating the webdav folder.
On this version i created the folder, it is also displayed but doubleclick on that ends in a 405.
```
"GET /user/webdav/ HTTP/2.0" 405 42
```
While trying to create folder (tmp) from the interface brings a:
```
"MKCOL /user/webdav/tmp/ HTTP/2.0" 405 42
```
> How can someone who is starting from scratch reproduce this behavior as minimally as possible?

I guess using the official caddy installscript to run with `curl`, add the filemanager extension and set it up as above.

By the way, i am really in love with the new default look of this plugin, but this is not an issue! ;)

**Comment by hacdias** [comment]
Hello @tchncs! First of all, thanks! 😄 Second: I can't reproduce this error 😕 What else do you have on your Caddyfile?

**Comment by hacdias** [comment]
uh, can you try cleaning the cache?

**Comment by tchncs** [comment]
Hi again, @hacdias :) 

The full entry for this subdomain contains:

```
users.domain {
        tls mail@adress {
                key_type rsa4096
        }
        gzip
        header / {
                Strict-Transport-Security "max-age=31536000;"
        }
        basicauth /user user verysecure

        filemanager /user {
                show            /home/mh-users/user

                allow_new       true
                allow_edit      true
                block           /my/secretfile
                whiteowl:
                allow_command   git
        }
        root /home/mh-users
        log /var/log/caddy/mhusers_access.log
        errors /var/log/caddy/mhusers_errors.log
}
```

Which cache do you mean exactly?

**Comment by hacdias** [comment]
The Caddyfile seems fine. This is really strange because everything is working here.

I'm referring to the browser cache. Maybe it hasn't updated the JS files. Only *maybe*.

**Comment by tchncs** [comment]
Very silly question:
Isn't cache only available via plugin?
I have no clue where it could be located.

```
/tmp # l cadd
No matches for: `arguments', `files', or `file'
/tmp # l .cadd
No matches for: `arguments', `files', or `file'
```

**Comment by hacdias** [comment]
No no. The browser cache: on Chrome, Firefox, whatever the browser your using.

**Comment by hacdias** [comment]
I'm too having troubles with drag'n'drop but not with uploading :/ Hope the fix is the same.

**Comment by tchncs** [comment]
Aww sure.
So i just opened a second browser which never saw this page before.
Ended in `INVALID_RESPONSE` and caddy tells about `405 42`.
I don't see how but maybe it helps to mention that i am using Archlinux?

**Comment by hacdias** [comment]
I think I just found the source of the problem 😄 let's see.

**Comment by tchncs** [comment]
I should have had mention, that, when i create a random folder from the console, it works like a charm.
It only affects the folder called `webdav`.

**Comment by hacdias** [comment]
The `webdav` folder is something internal. Don't worry about that name. 😄 I think I found the problem (at least part of it) or I found another problem. I'm going to fix this and hope the fix is the same.

**Comment by tchncs** [comment]
> The webdav folder is something internal.

Yeah i know, i just tried to tell that it's only affects this folder. :P 

> I'm going to fix this

Wooo, hoping the best! :)

**Comment by hacdias** [comment]
I just pushed code. It fixes some things. I'm just not sure if it fixes *this* but I hope it does. Can you build it from source just to check, please?

**Comment by tchncs** [comment]
Aww, on my last try to compile caddy with extentions i failed. :(
I tried to explain my problem in the forumthread... .

**Comment by hacdias** [comment]
Oh, you just have do add `_ "github.com/hacdias/caddy-filemanager"` to the `import` section on `$GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go` and then compile 😄

**Comment by tchncs** [comment]
Huh... odd... so i made it just too difficult for myself on my last try... it worked... . O.o

However, the 404/405 issue is sadly still the same.

**Comment by hacdias** [comment]
Just to make sure: you updated the repository there?

**Comment by tchncs** [comment]
Yeah i made something wrong and i am sorry.
I updated the filemanager repository but the revision is still the same after rebuilding caddy.
After that i ran `go clean github.com/hacdias/caddy-filemanager` and it is still the same.
Yeah, have still things to learn about go... a bunch.

**Comment by hacdias** [comment]
No problem. Execute:

```
go get -u github.com/hacdias/caddy-filemanager
cd $GOPATH/src/github.com/hacdias/caddy-filemanager
go generate
```

And after that build and run caddy. Check if the revision changes. If so, tell me if you still have the error.

**Comment by tchncs** [comment]
Whooops, it did not purged the files as expected!
I used `go generate github.com/hacdias/caddy-filemanager` instead.
However, revision is now correctly but the issue sadly just there.

**Comment by hacdias** [comment]
😢 I'll try to find out what's the problem. Apparently I fixed another bug I found while searching for this one. My problem is that I'm not being able to reproduce it.

**Comment by tchncs** [comment]
Hmm i see that.
I am not sure what else i can give you to reproduce... .
I simply  added caddy to the a group the affected user is in go make it able to handle the files.
But i guess this description would only help on a 403 issue. :/
And since now everything is built from git so far we should be more or less at the same state.. .

**Comment by tchncs** [comment]
I changed the webdav path using `webdav       ../tmp` (everything else ends with `/user/user/folder`.
The result is: `PUT /user/tmp/H6E6ta86_400x400.jpg HTTP/2.0" 501 20`

**Comment by hacdias** [comment]
@tchncs you're not supposed to need to change the `webdav` option. That is kind of a magic URL. It doesn't have a *physical* counterpart. I still can't reproduce this error. Everything is working fine here.

You're *not* supposed to create a `webdav` folder. If you create a folder with that name, you won't be able to access it. It's like a reserved name.

Make me a favor, since I can't reproduce this:

1. Pick a file and note down it's URL (e.g. `/user/testimage.jpg`)
2. Open the URL with `/webdav` on it in a separate tab (e.g. `/user/webdav/testimage.jpg`).

Do you get 404? Or is the file shown as it was supposed to happen?

Sorry for this 😞

**Comment by tchncs** [comment]
Okey, i removed the tmp and webdav folder.
Uploading/Editing still gives a 404.
Opening a file with /webdav/ in it, gives the raw output of the file.

**Comment by hacdias** [comment]
So, the opening works. It means the file *exists* and the URLs are right. The editing, when you save, also gives 404? 😲

**Comment by hacdias** [comment]
@tchncs some questions for you:

1. Can you rename files?
2. Can you move files?
3. Can you save files?
4. Can you see raw files?
5. Can you open images (or music, or video) and see them?
6. Can you delete files?
7. Can you create files?
8. Can you upload files?

Please answer yes or no for every question and if the answer is 'no' please give me the error, please. I'm really trying to see what's wrong here.

Since you started this issue, have you changed your Caddyfile? If so, can you post it here again, please?

*Sorry for this.*

**Comment by tchncs** [comment]
Oh my god, since you fixed the multipath issue, i was able on a second user again where it worked.
So i unified the folder permissions and it worked! 😮 
I am so sorry but i only had 403 issues on permission problems so i did not know this would be an option to look at (but i guess i tried it anyway last night but was quite sleepy).

>    Can you rename files?

Yes

>    Can you move files?

**No** - no action happens on click
Yes - via drag&drop

>    Can you save files?

Yes

>    Can you see raw files?

Yes

>    Can you open images (or music, or video) and see them?

Yes

>    Can you delete files?

**No** - the log shows 200 for GET the js/css stuff on click

>    Can you create files?

Yes

>    Can you upload files?

Yes

> Since you started this issue, have you changed your Caddyfile? 

Yes, i added the entries for two new directorys as you have seen in the forum.

**Comment by hacdias** [comment]
Hello again @tchncs! Let's see then.

> > Can you move files?
> 
> No - no action happens on click
> Yes - via drag&drop

Files can be moved via drag&drop or clicking in that arrow in the top bar after selecting the file.

![image](https://cloud.githubusercontent.com/assets/5447088/22182155/08a4dda2-e096-11e6-8467-6b2a10a9e98b.png)

![image](https://cloud.githubusercontent.com/assets/5447088/22182163/1db6a216-e096-11e6-8581-621b5b0f120b.png)

Does that menu work?

> > Can you delete files?
> 
> No - the log shows 200 for GET the js/css stuff on click

Please check the console log. It usually opens when you click F12 inside your browser.

![image](https://cloud.githubusercontent.com/assets/5447088/22182168/459e1688-e096-11e6-83c9-553d69e31e5b.png)

Try to delete a file and tell me what appears there, please.

---

By the way, you can just click "F1" to get help and some tips. 😄

**Comment by tchncs** [comment]
#### Move

I ment the menu and it don't work. ;)
```
[22/Jan/2017:12:44:07 +0100] "GET /user/_filemanagerinternal/css/fonts.css HTTP/2.0" 200 695
[22/Jan/2017:12:44:07 +0100] "GET /user/_filemanagerinternal/css/styles.css HTTP/2.0" 200 3824
[22/Jan/2017:12:44:07 +0100] "GET /user/_filemanagerinternal/css/normalize.css HTTP/2.0" 200 2237
[22/Jan/2017:12:44:07 +0100] "GET /user/_filemanagerinternal/js/common.js HTTP/2.0" 200 3618
[22/Jan/2017:12:44:07 +0100] "GET /user/_filemanagerinternal/js/listing.js HTTP/2.0" 200 3492
[22/Jan/2017:12:44:20 +0100] "GET /user/log/ HTTP/2.0" 200 343
[22/Jan/2017:12:44:22 +0100] "GET /user/ HTTP/2.0" 200 331
```

```
TypeError: event.srcElement is undefined[More informations]  listing.js:450:1
	listing.moveSelected https://users.domai.n/user/_filemanagerinternal/js/listing.js:450:1
```

#### Delete

```
ReferenceError: event is not defined[More informations]  common.js:296:3
	deleteOnListing https://users.domai.n/user/_filemanagerinternal/js/common.js:296:3
unreachable code after return statement[More informations]  common.js:194:2
unreachable code after return statement[More informations]  common.js:211:2
```
^using button + DEL key
(More informations redirects to the firefox docs)

I often forget the console log, sorry about that. :)
And the F1 menu is quite cool 👍

**Comment by hacdias** [comment]
Just pushed two fixes. Can you please try them out? 😄

**Comment by tchncs** [comment]
No. Just kidding. :P 
Move works now. 🎉 
Delete still doesn't work, no console log from the browser available to show and no change in the caddy log (200).

**Comment by tchncs** [comment]
Oh, wait, there is an entry in the browserlog but it is blank!
```
  common.js:312:7
```

**Comment by hacdias** [comment]
I tried using Firefox and it worked. Can you check the logs? It may contain something like `DELETE http://url.goes/in/here`.

**Comment by tchncs** [comment]
Uhm... odd?
I opened Chromium -> deleted -> worked
Cleared Firefox's cache -> deleted -> nope -> restarted firefox -> deleted -> nope

It does not show the `DELETE` entry when using Firefox but as expected in Chromium.
Just in case i tried two users but it is the same everywhere.

**Comment by hacdias** [comment]
And you don't get any error? Are you using the latest version of FF? I can
delete with both :/

**Comment by tchncs** [comment]
Update: tried Firefox from an other computer and it works.
So i guess Firefox did not cleanly deleted the cache or something odd else.
Using `50.1.0` however, it is with a 99,999% chance my problem, somewhere (not a plugin).
Let's close this issue (as the issue itself is already fixed anyway).

Thanks for your quick and friendly help! 🥇

**Comment by hacdias** [comment]
You're welcome! Anything else, just come over here. Hope the plugin shows
itself useful!
